In [17]:
import numpy as np
import os.path

a= np.random.rand(4,3,3)*100
b= np.random.rand(4,1)*10
print('b='+str(b))

a=np.reshape(a,(4,-1))
print(a.shape)
print(b.shape)
a=np.append(a,b,axis=1)
print('a='+str(a.shape))

np.random.shuffle(a)

# x= np.empty((a.shape[0],1))
x= np.array([])
print(x)
# for i in range(a.shape[1]-1):
#     if i==0:
#         x= np.array(a[:,i]).reshape(-1,1)
#     else:
#         x=np.append(x,np.array(a[:,i]).reshape(-1,1),axis=1)


y= np.array(a[:,a.shape[1]-1])
print('x='+str(x.shape))
print('y='+str(y))
print(y.shape)
print('a='+str(a))
print('x='+str(x))



b=[[5.35842042]
 [9.61887101]
 [3.25430998]
 [3.38521404]]
(4, 9)
(4, 1)
a=(4, 10)
[]
x=(0,)
y=[3.38521404 3.25430998 9.61887101 5.35842042]
(4,)
a=[[ 2.92450537 87.20204091  2.21105485 63.93762383  6.56571586 52.23893914
  49.21682811 21.00313123 73.85165254  3.38521404]
 [95.35684302 58.64875458 29.10987282  3.64457431 95.47642653  1.8471273
   6.23766849 77.71944608 94.23515484  3.25430998]
 [17.82446976 54.52344839 52.14012936 71.61492864 64.76732139 52.98645222
   6.29601078 37.75175609 54.29810164  9.61887101]
 [94.69014913 17.84727644 82.74274031 37.69172656 73.63021662  0.94115195
  15.93097603 18.31512314 64.03084427  5.35842042]]
x=[]


In [12]:
a= np.random.rand(4,3,3)*100
print('a='+str(a))
dim = a.shape
a= np.reshape(a,(4,-1))
print(a.shape)
np.random.shuffle(a)
print(a.shape)
a= np.reshape(a,dim)
print(a.shape)
print('-----------------------')
print('a='+str(a))

a=[[[77.85669384 21.15744454 85.60935817]
  [18.04427172 64.69797987 18.49422401]
  [53.93010688 14.17338002 10.15914006]]

 [[78.62463883 21.64971723 66.34641763]
  [10.56921806 46.28444135 18.67057289]
  [22.68642786 10.88162367 82.46025505]]

 [[62.04710427 72.59085189 20.52069669]
  [34.16088279 17.35732006 12.91627889]
  [27.35493129 60.11947292 86.96850552]]

 [[46.7445189  37.91918311 53.60815009]
  [75.26265247 21.24821586 42.64600539]
  [16.60715105 74.34399452 55.969127  ]]]
(4, 9)
(4, 9)
(4, 3, 3)
-----------------------
a=[[[46.7445189  37.91918311 53.60815009]
  [75.26265247 21.24821586 42.64600539]
  [16.60715105 74.34399452 55.969127  ]]

 [[62.04710427 72.59085189 20.52069669]
  [34.16088279 17.35732006 12.91627889]
  [27.35493129 60.11947292 86.96850552]]

 [[78.62463883 21.64971723 66.34641763]
  [10.56921806 46.28444135 18.67057289]
  [22.68642786 10.88162367 82.46025505]]

 [[77.85669384 21.15744454 85.60935817]
  [18.04427172 64.69797987 18.49422401]
  [53.93010688

In [ ]:
def shuffle_examples(X,Y):
    dim= X.shape
    X= np.reshape(X,(X.shape[0],-1))
    Y=Y.reshape(-1,1)
    X= np.append(X, Y, axis=1)
    np.random.shuffle(X)
    
    A=np.array([])
    
    for i in range(X.shape[1]-1):
        if i==0:
            A= np.array(X[:,i]).reshape(-1,1)
        else:
            A=np.append(A,np.array(X[:,i]).reshape(-1,1),axis=1)

    Y= np.array(X[:,X.shape[1]-1])
    
    A= np.reshape(A,dim)
    
    return A,Y
    

In [4]:
import os.path
from numpy import genfromtxt

A= np.random.randn(3,2)
np.savetxt('2darray.csv', A, delimiter=',', fmt='%f')


if(os.path.exists('2darray.csv')==True):
        A = genfromtxt('2darray.csv', delimiter=',')
        print(A)
        



[[-0.485456  1.492446]
 [-0.852342 -1.644605]
 [ 0.115609 -1.54102 ]]


In [6]:
# A= np.random.randn(3,2)
# np.save('2darray.npy', A)


# if(os.path.exists('2darray.npy')==True):
#         A = np.load('2darray.npy')
#         print(A)

a=np.array([])
np.save('2darray.npy', a)
np.save('train_images.npy',a)
np.save('train_labels.npy',a)
np.save('test_images.npy',a)
np.save('test_labels.npy',a)
        


In [ ]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
import os.path
from saveDataset import save_data

# Helper libraries
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
import glob, os
import re

# Pillow
import PIL
from PIL import Image



# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")
 
# evaluate loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(X, Y, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))